### ISSUE TITLE
LogViewer plugin: adapt to slf4j

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#166]
[LogViewer](https://github.com/freedomotic/freedomotic/blob/master/plugins/devices/frontend-java/src/main/java/com/freedomotic/jfrontend/LogViewer.java) requires some adjustments to show log messages with slf4j.

How it works
The plugin GUI shows a combobox where you can select a log level (ALL,INFO,WARN,ERROR) and view all messages related to that level
https://www.youtube.com/watch?v=cvxdhAfcs-Y

**Comment by mcicolella** [comment]
@Helltux Can you take a look at this?

**Comment by Helltux** [comment]
yes I can look at times. I think I need to learn something more about java Loggin, which is great!

I understand the problem correctly, that you by the change from Java loggin to slf4j this can no longer displayed? So do you want to change everything in the future to slf4j? Because is only important that the plugin can display the slf4j rows?

**Comment by mcicolella** [comment]
@Helltux Yes we are switching completely to Slf4j

**Comment by mcicolella** [comment]
@Helltux Any news?

**Comment by Helltux** [comment]
Oh yes, sry i'm back to a paid job. I'll see if I find time.
But I have not yet found a way to get the logs from the root logger.

**Comment by mcicolella** [comment]
@P3trur0 Any idea about fixing?

**Comment by P3trur0** [comment]
@mcicolella what is the actual problem? Is the plugin dependency to be updated to work with SLF4J, right?

**Comment by mcicolella** [comment]
@P3trur0 Yes we should list all log messages filtered by level.

**Comment by mcicolella** [comment]
Fixed in d7b185508781fe07ac8ce6e8843405bb2e49486c
