### ISSUE TITLE
Event UUID is commented out

### ISSUE THREAD

**Issue by P3trur0** [freedomotic/freedomotic#246]
In order to support a proper identification of each triggered event, it should be necessary to mark each of them with their proper identification UUID. Although originally supported, [here](https://github.com/freedomotic/freedomotic/blob/master/framework/freedomotic-core/src/main/java/com/freedomotic/api/EventTemplate.java#L119) there are a couple of code lines generating events UUID commented out.

**Comment by mcicolella** [comment]
@enriconicoletti what about?

**Comment by mcicolella** [comment]
@P3trur0 
Commands have their unique UUID https://github.com/freedomotic/freedomotic/blob/a4967cd33bb4ba967d9c7ba20304f084fc166b34/framework/freedomotic-core/src/main/java/com/freedomotic/reactions/Command.java#L95

Maybe in the EventTemplate class the code is commented because the method UidGenerator.getNextUid() is not used and replaced by UUID.randomUUID().toString()

**Comment by P3trur0** [comment]
@mcicolella ok then. So what about to add it in the `fillPayloadWithDefaults` method of `EventTemplate`?

**Comment by mcicolella** [comment]
@P3trur0 Ok! And also a getUUID() method.
