### ISSUE TITLE
Renderer class throws an exception at startup

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#354]
At Freedomotic startup the following exception is raised by [Renderer.java](https://github.com/freedomotic/freedomotic/blob/0c93fd6f496813a45f43d82025a912a6c7f2b046/plugins/devices/frontend-java/src/main/java/com/freedomotic/jfrontend/Renderer.java#L580) class 

`
2017-10-09 16:32:52,342 ERROR [AWT-EventQueue-0] - Error while store transform context!
`
It seems related to 0c93fd6f496813a45f43d82025a912a6c7f2b046

**Comment by bezmax** [comment]
Hello @mcicolella . I will investigate this issue.

**Comment by bezmax** [comment]
The problem was a call to `restoreTransformContext` from within the routine that works with a separate `Graphics` of a BufferedImage and does not have any transform context saved. Given that the buffered image will not need any more changes (which I tried to emphasize by extracting that to separate method) - there is no need to restore it's original transformation, so I removed it.
