### ISSUE TITLE
Reduce size of ARM Docker images

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#401]
We have two Docker [images](https://github.com/freedomotic/freedomotic/tree/master/scripts/docker) for ARM32 and ARM64. 
We are trying to reduce their size as possible (https://hub.docker.com/r/freedomotic/freedomotic/tags/).

**Comment by mcicolella** [comment]
@thobalose what about?

**Comment by thobalose** [comment]
@mcicolella I see that: 

- The parent [image](https://hub.docker.com/r/maidbot/resin-raspberrypi3-qemu/tags/) for `arm64` is `181MB` and your build being `546 MB`

- The parent [image](https://hub.docker.com/r/resin/armv7hf-debian-qemu/tags//) for `armhf` is `37MB` and your build being `415 MB`

Will have a look.

**Comment by mcicolella** [comment]
@thobalose any news?

**Comment by thobalose** [comment]
Hi @mcicolella ,

Had a lot on my plate the past week and haven't had time to look at this.
I will, however, give feedback by next week.

**Comment by mcicolella** [comment]
@thobalose any news?

**Comment by thobalose** [comment]
Hi @mcicolella I am looking at https://docs.docker.com/engine/userguide/eng-image/multistage-build/ to do this. 

Will keep you posted.

**Comment by mcicolella** [comment]
@thobalose are you still on this?

**Comment by thobalose** [comment]
Hi @mcicolella ,

Have you had a look into building from https://hub.docker.com/r/arm64v8/openjdk/tags/. I am having a couple of build errors on my side. I understand they are related to https://github.com/moby/moby/issues/35447 and that's why you are pulling from https://hub.docker.com/r/maidbot/resin-raspberrypi3-qemu/tags/. 

Sorry but I am having a hard time working on this.
